apiVersion: cloudfairy.dev/v1
kind: CloudfairyLibraryModule
metadata:
  namespace: cloudfairy
  name: whoami
spec:
  runtime: helm
  helmMapping:
    properties:
      replicas: whoami.replicaCount
  vendor: cloudfairy
  displayName: Whoami
  dependencies: []
  interface:
    - env
  entry:
    default: ./whoami
  validation: []
    # - kind: query
    #   name: "Check Deployment"
    #   query: "deployment/{{ properties.localName }}"
    #   condition: "{{status.availableReplicas}} >= 1"
    #   timeout: 60000 # 60 seconds
    # - kind: query
    #   name: "Check Service"
    #   query: "service/{{ properties.localName }}-svc"
    #   condition: 'typeof {{status.loadBalancer}} !== "undefined"'
    #   timeout: 60000 # 60 seconds
  output: []
    # - name: serviceName
    #   query: "service/{{ properties.localName }}-svc"
    #   value: "{{metadata.name}}"
    # - name: servicePort
    #   query: "service/{{ properties.localName }}-svc"
    #   value: "{{spec.ports[0].port}}"
    # - name: availabilty
    #   query: "deployment/{{ properties.localName }}"
    #   value: "{{status.availableReplicas}}"
  properties:
    - name: replicas
      displayName: "Whoami Replicas"
      type: number
      defaultValue: 1
    # - name: env_vars
    #   displayName: "Extra Environment Variables"
    #   type: keyvalue
    #   defaultValue:
    #     cloudfairy: "true"